# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.5/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.5/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pr0zac/Development/Expresso-Node

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pr0zac/Development/Expresso-Node

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.5/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.5/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/pr0zac/Development/Expresso-Node && $(CMAKE_COMMAND) -E cmake_progress_start /Users/pr0zac/Development/Expresso-Node/CMakeFiles /Users/pr0zac/Development/Expresso-Node/Holepoke/CMakeFiles/progress.marks
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f CMakeFiles/Makefile2 Holepoke/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pr0zac/Development/Expresso-Node/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f CMakeFiles/Makefile2 Holepoke/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f CMakeFiles/Makefile2 Holepoke/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f CMakeFiles/Makefile2 Holepoke/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/pr0zac/Development/Expresso-Node && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
Holepoke/CMakeFiles/holepoke.dir/rule:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f CMakeFiles/Makefile2 Holepoke/CMakeFiles/holepoke.dir/rule
.PHONY : Holepoke/CMakeFiles/holepoke.dir/rule

# Convenience name for target.
holepoke: Holepoke/CMakeFiles/holepoke.dir/rule
.PHONY : holepoke

# fast build rule for target.
holepoke/fast:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/build
.PHONY : holepoke/fast

endpoint.o: endpoint.cc.o
.PHONY : endpoint.o

# target to build an object file
endpoint.cc.o:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/endpoint.cc.o
.PHONY : endpoint.cc.o

endpoint.i: endpoint.cc.i
.PHONY : endpoint.i

# target to preprocess a source file
endpoint.cc.i:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/endpoint.cc.i
.PHONY : endpoint.cc.i

endpoint.s: endpoint.cc.s
.PHONY : endpoint.s

# target to generate assembly for a file
endpoint.cc.s:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/endpoint.cc.s
.PHONY : endpoint.cc.s

fsm.o: fsm.cc.o
.PHONY : fsm.o

# target to build an object file
fsm.cc.o:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/fsm.cc.o
.PHONY : fsm.cc.o

fsm.i: fsm.cc.i
.PHONY : fsm.i

# target to preprocess a source file
fsm.cc.i:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/fsm.cc.i
.PHONY : fsm.cc.i

fsm.s: fsm.cc.s
.PHONY : fsm.s

# target to generate assembly for a file
fsm.cc.s:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/fsm.cc.s
.PHONY : fsm.cc.s

holepoke.pb.o: holepoke.pb.cc.o
.PHONY : holepoke.pb.o

# target to build an object file
holepoke.pb.cc.o:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/holepoke.pb.cc.o
.PHONY : holepoke.pb.cc.o

holepoke.pb.i: holepoke.pb.cc.i
.PHONY : holepoke.pb.i

# target to preprocess a source file
holepoke.pb.cc.i:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/holepoke.pb.cc.i
.PHONY : holepoke.pb.cc.i

holepoke.pb.s: holepoke.pb.cc.s
.PHONY : holepoke.pb.s

# target to generate assembly for a file
holepoke.pb.cc.s:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/holepoke.pb.cc.s
.PHONY : holepoke.pb.cc.s

network.o: network.cc.o
.PHONY : network.o

# target to build an object file
network.cc.o:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/network.cc.o
.PHONY : network.cc.o

network.i: network.cc.i
.PHONY : network.i

# target to preprocess a source file
network.cc.i:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/network.cc.i
.PHONY : network.cc.i

network.s: network.cc.s
.PHONY : network.s

# target to generate assembly for a file
network.cc.s:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/network.cc.s
.PHONY : network.cc.s

node_peer.o: node_peer.cc.o
.PHONY : node_peer.o

# target to build an object file
node_peer.cc.o:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/node_peer.cc.o
.PHONY : node_peer.cc.o

node_peer.i: node_peer.cc.i
.PHONY : node_peer.i

# target to preprocess a source file
node_peer.cc.i:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/node_peer.cc.i
.PHONY : node_peer.cc.i

node_peer.s: node_peer.cc.s
.PHONY : node_peer.s

# target to generate assembly for a file
node_peer.cc.s:
	cd /Users/pr0zac/Development/Expresso-Node && $(MAKE) -f Holepoke/CMakeFiles/holepoke.dir/build.make Holepoke/CMakeFiles/holepoke.dir/node_peer.cc.s
.PHONY : node_peer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... holepoke"
	@echo "... rebuild_cache"
	@echo "... endpoint.o"
	@echo "... endpoint.i"
	@echo "... endpoint.s"
	@echo "... fsm.o"
	@echo "... fsm.i"
	@echo "... fsm.s"
	@echo "... holepoke.pb.o"
	@echo "... holepoke.pb.i"
	@echo "... holepoke.pb.s"
	@echo "... network.o"
	@echo "... network.i"
	@echo "... network.s"
	@echo "... node_peer.o"
	@echo "... node_peer.i"
	@echo "... node_peer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/pr0zac/Development/Expresso-Node && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

